name: 更新业绩报表_em
on:
  workflow_dispatch:
  # 定时触发，UTC->Beijing 增加8小时得到北京时间
  # * 1 * * * -> 09:00
  # schedule:
  #   - cron: '26 19 * * *'
jobs:
  yjbb_em0:
    secrets: inherit
    with:
      env_start: 0
    uses: ./.github/workflows/get_yjbb_em.yml
